Feature/submission upload
SELab-2/UGent-6 pull request #249
Opened 2024-05-05 16:03 UTC by AWerbrouck

files uploaden kan nu adhv submissions

het zijn maar een paar kleine changes, maar enkele hiervan zijn aan de apifetch dus bekijk deze goed.

2024-05-08 14:08 UTC, arnedierick requested changes
Op het eerste zicht zien alle changes er goed uit. Het is intuïtief. Wanneer ik echter een indiening wil maken ondervind ik een paar problemen:

- in de file manager die ik open kan ik geen individuele bestanden selecteren
- Telkens als ik indien krijg ik een console error, zelfs al is de indiening "succesvol". Ik krijg ook geen confirmatie of de indiening geslaagd is. Probeer die bug op te vangen en kijk eens naar [Ant Design's message component](https://ant.design/components/message)
- Als ik een gemaakte indiening wil downloaden, dan krijg ik een zip map die ik corrupt is. (Windows kan ze niet openen)

Over de apifetch en die technische zaken kan ik niet goed oordelen of je daar wel alles goed doet, dat is meer iets voor @usserwoutV2 om over te oordelen, maar de dingen die ik aanhaal, kan je al aan werken

2024-05-09 11:51 UTC, AWerbrouck commented on frontend/src/pages/submit/components/SubmitForm.tsx
@usserwoutV2 hier is de bug

2024-05-09 16:43 UTC, AWerbrouck commented
@arnedierick kan je nu nog eens proberen, het zou nu terug moeten werken.

2024-05-09 16:49 UTC, AWerbrouck commented
ik ga ook nog de upload hier doen

2024-05-09 23:24 UTC, usserwoutV2 commented
Ik heb even gecheckt en het ziet er goed uit. Ik heb wel nog enkele typescript errors gezien in de code (ik heb deze even opgelost).  Ik heb ook eens `Tree` naar `Tree.DirectoryTree` aangepast waardoor het net iets duidelijker is wat files en directories zijn. Verder heb ik de functionaliteit getest en heb geen problemen kunnen vinden. 

https://github.com/SELab-2/UGent-6/blob/089a961085b40e9c3983b49f239610e0f4da05f8/frontend/src/pages/submit/Submit.tsx#L39-L45
Ik weet niet wat je hier juist doet, maar dit zal waarschijnlijk voor problemen veroorzaken als het op de server gehost wordt (omdat we dan niet meer in localhost zitten). Als je de courseId wilt krijgen dan kan je dat best via `const course = useCourse()` of via `const {courseId} = useParams()`. Om naar de route te gaan gebruik je best de `AppRoutes.SUBMISSION.replace(':courseId', '...').replace(':projectId', ...).replace(':submissionId',...)` in plaats van `/courses/${courseId}/projects/${projectId}/submissions/${submissionId}`.

2024-05-13 15:26 UTC, closed without merging