Een groepcluster vullen met 1 request
SELab-2/UGent-6 pull request #252
Opened 2024-05-09 09:06 UTC by arnedierick

Ik heb een route toegevoegd /api/clusters/{clusterid}/fill die de groepen van een bestaande cluster volledig overschrijft. Het is belangrijk om op te merken dat dit de hele cluster reset. Het gaat als volgt:

1. checkt of de user toegang heeft tot de cluster en vraagt hem op
2. vraagt alle groepen op van de cluster
3. checkt of de request niet meer groepen bevat dan toegestaan in de cluster
4. checkt of de request geen groepen bevat die groter zijn dan de capaciteit van de cluster
5. verwijdert alle huidige groepen van de cluster
6. voegt alle groepen toe zoals aangegeven in de request (doet geen extra checks op de users omdat ik niet denk dat dit nodig is)
7. returnt HTTP OK

2024-05-09 09:07 UTC, arnedierick commented
Ik ga hier nog een backend test voor schrijven, dan ga ik de PR open zetten

2024-05-09 09:08 UTC, Aqua-sc commented
@arnedierick ik zal anders de testen wel schrijven. Kheb basically alle andere testen ook aangepast (geupgrade) in mijn komende PR dus kneem deze er wel gwn bij shouldn't take long

2024-05-09 09:10 UTC, Aqua-sc commented
> checkt of de request niet meer groepen bevat dan toegestaan in de cluster

dit is geen ding, die count is gwn een (lowkey overbodig at this point) tellertje da bijhoudt hoeveel groepen er zijn. Das geen maximum fzo

2024-05-09 09:11 UTC, Aqua-sc commented
> voegt alle groepen toe zoals aangegeven in de request (doet geen extra checks op de users omdat ik niet denk dat dit nodig is)

Dit zou wel moeten gebeuren

2024-05-09 09:18 UTC, Aqua-sc requested changes

2024-05-09 09:18 UTC, Aqua-sc commented on backend/app/src/main/java/com/ugent/pidgeon/controllers/ClusterController.java
> +        }
Dit lijkt me overbodig aangezien je de GroupClusterEntity al hebt

2024-05-09 09:18 UTC, Aqua-sc commented on backend/app/src/main/java/com/ugent/pidgeon/controllers/ClusterController.java
> +        }
dit mag dus weg

2024-05-09 09:18 UTC, Aqua-sc commented on backend/app/src/main/java/com/ugent/pidgeon/controllers/ClusterController.java
> +            return ResponseEntity.status(HttpStatus.BAD_REQUEST).body("you made a group with too many members");
Ik zou dus voor elke groep checken in de clusterFillJson checken of

1. de groep een valid groep is & gekoppeld aan die cluster
2. er niet meer members zijn dan de maxSize
3. alle users valid users zijn die in de course zitten

Eenmaal dit voor alle groepen id request gecheckt is kunnen ze toegevoegd worden zoals je dit reeds doet

2024-05-09 10:14 UTC, arnedierick commented
> @arnedierick ik zal anders de testen wel schrijven. Kheb basically alle andere testen ook aangepast (geupgrade) in mijn komende PR dus kneem deze er wel gwn bij shouldn't take long

Oeps, ik heb dit ondertussen al gedaan. je kan die test aanpassen als je hem wil veranderen

2024-05-09 10:15 UTC, arnedierick commented on backend/app/src/main/java/com/ugent/pidgeon/controllers/ClusterController.java
> +        }
Ik doe dit omdat een GroupClusterEntity niet de groep-info bevat om alle groepen te verwijderen

2024-05-09 10:15 UTC, arnedierick commented
Ik zal de requested changes implementeren na de vergadering

2024-05-09 10:18 UTC, Aqua-sc commented on backend/app/src/main/java/com/ugent/pidgeon/controllers/ClusterController.java
> +        }
`GroupRepository.findAllByClusterId(ClusterId)` zou ik hier dan voor gebruiken

2024-05-10 12:41 UTC, Aqua-sc commented
Top, ik zal hiernaar kijken wanneer ik klaar ben met de andere testen te schrijven (zal waarschijnlijk pas morgen zijn tho)

2024-05-12 10:32 UTC, arnedierick commented
Top, de changes die je gedaan hebt maken de route veiliger en makkelijker om te gebruiken. Je mag mergen!

2024-05-12 11:46 UTC, Aqua-sc approved these changes

2024-05-12 11:47 UTC, merged